package coname

var generatedSuffixes = []string{
	"& Co.",
	"& Co. GmbH",
	"& Co. L.L.C.",
	"(Pty.) Ltd.",
	"(cn)",
	"(es)",
	"(gb)",
	"(uk)",
	"(us)",
	"A.C.",
	"A.O.",
	"A.Ş.",
	"A/S",
	"AB",
	"AD",
	"AG",
	"AG & Co. KG",
	"AG & Co. KGaA",
	"AG und Co. KG",
	"AG und Co. KGaA",
	"AO",
	"AS",
	"ASA",
	"ASBL",
	"ASC L.L.C.",
	"AT",
	"Akciju sabiedrība",
	"Aksjeselskap",
	"Aktiebolag",
	"Aktiengesellschaft",
	"Aktieselskab",
	"Allmennaksjeselskap",
	"Anonim Ortaklık",
	"Anonim Şirket",
	"Anpartsselskab",
	"ApS",
	"Asociación Civil",
	"B.V.",
	"B.V.B.A.",
	"Berhad",
	"Besloten vennootschap",
	"Besloten vennootschap met beperkte aansprakelijkheid",
	"Betéti Társasá",
	"Bhd.",
	"Bt.",
	"C.V.",
	"CJSC",
	"CRL",
	"Ccc",
	"Chartered",
	"Chtd.",
	"Closed Joint Stock Company",
	"Co-op.",
	"Co.",
	"Co. (Pty.) Ltd.",
	"Co. Inc.",
	"Co. L.L.C.",
	"Co. Ltd.",
	"Co. OJSC",
	"Co. P.J.S.C.",
	"Co. W.L.L.",
	"Co.,Ltd.",
	"Commanditaire vennootschap",
	"Company",
	"Company Inc.",
	"Company L.P.",
	"Company Limited",
	"Company Ltd.",
	"Coop.",
	"Cooperativa de Responsabilidade Limitada",
	"Cooperative",
	"Corp.",
	"Corporation",
	"Corporation K.K.",
	"Corporation S.p.A.",
	"Cwmni Cyfyngedig Cyhoeddus",
	"Cyf",
	"Cyfyngedig",
	"De vennootschap onder firma",
	"Delniška družba",
	"Družba z neomejeno odgovornostjo",
	"Družba z omejeno odgovornostjo",
	"E.B.V.B.A.",
	"E.S.E.",
	"EAD",
	"EOOD",
	"Eenpersoons besloten vennootschap met beperkte aansprakelijkheid",
	"Egyéni Cég",
	"Egyéni Vállalkozó",
	"Empresa Social del Estado",
	"G.K.",
	"GMK",
	"GP",
	"GSK",
	"GUP",
	"GbR",
	"Ges.m.b.H.",
	"Gesellschaft bürgerlichen Rechts",
	"Gesellschaft m.b.H.",
	"Gesellschaft mit beschränkter Haftung",
	"GmbH",
	"GmbH & Co OHG",
	"GmbH & Co.",
	"GmbH & Co. KG",
	"GmbH & Co. KGaA",
	"GmbH und Co OHG",
	"GmbH und Co.",
	"GmbH und Co. KG",
	"GmbH und Co. KGaA",
	"Godo Kaisha",
	"Gomei Kaisha",
	"Goshi Kaisha",
	"HAAO",
	"HB",
	"Halka Açık Anonim Ortaklık",
	"Handelsbolag",
	"Hapja Hoesa'",
	"Hapmyoung Hoesa",
	"IP",
	"Inc.",
	"Incorporated",
	"Incorporée",
	"JSC",
	"JSCB",
	"Joint Stock Commercial Bank",
	"Joint Stock Company",
	"Julkinen osakeyhtiö",
	"Jusik Hoesa",
	"K.K.",
	"K/S",
	"KB",
	"KG",
	"KG GmbH & Co.",
	"KGaA",
	"Kabushiki Kaisha",
	"Kft.",
	"Kht.",
	"Kkt.",
	"KolG",
	"Kolektif Şirket",
	"Koll. Şti.",
	"Kollektivgesellschaft",
	"Kom. Şti",
	"KomAG",
	"Komandit Şirket",
	"Komanditna družba",
	"Kommanditaktiengesellschaft",
	"Kommanditbolag",
	"Kommanditgesellschaft",
	"Kommanditgesellschaft auf Aktien",
	"Kommanditselskab",
	"Koop.",
	"Kooperatif Şirket",
	"Korlátolt Felelősségű Társaság",
	"Kv.",
	"Közhasznú Társaság",
	"Közkereseti Társaság",
	"Közös Vállalat",
	"L.C.",
	"L.L.C.",
	"L.L.L.P.",
	"L.L.P.",
	"L.O.",
	"L.P.",
	"L.Ş.",
	"Limitada",
	"Limited",
	"Limited Company",
	"Limited Liability Companies",
	"Limited Liability Company",
	"Limited Liability Limited Partnership",
	"Limited Liability Partnership",
	"Limited Ortaklık",
	"Limited Partnership",
	"Limited Şirket",
	"Limitée",
	"Ltd.",
	"Ltd. & Co. KG",
	"Ltd. Co.",
	"Ltd. Company",
	"Ltd. Şti.",
	"Ltda.",
	"Ltée",
	"Maatschap",
	"Mts",
	"N.A.",
	"N.V.",
	"N.V. Nv",
	"NK",
	"NL",
	"Naamloze vennootschap",
	"National Association",
	"Nin'i Kumiai",
	"No Liability",
	"Nonprofit Kft.",
	"Nyilvánosan Működő Részvénytársaság",
	"Nyrt.",
	"OAO",
	"OG",
	"OHG",
	"OJSC",
	"OOD",
	"OOO",
	"Open Joint Stock Company",
	"Osakeyhtiö",
	"Oy",
	"Oyj",
	"P.C.",
	"P.J.S.C.",
	"P.P.",
	"P.S.C.",
	"P/L",
	"PJSC",
	"PLLC",
	"PT",
	"PT Tbk",
	"PartG",
	"Partnerschaftsgesellschaft",
	"Perseroan Terbatas",
	"Perseroan Terbatas Terbuka",
	"PrJSC",
	"Private Limited",
	"Private Limited Company",
	"Professional Corporation",
	"Professional Limited Liability Company",
	"Proprietary Limited",
	"Przedsiębiorstwo Państwowe",
	"Pte. Ltd.",
	"Pty.",
	"Pty. Limited.",
	"Pty. Ltd.",
	"Public Joint Stock Company",
	"Public Limited Company",
	"Pvt. Ltd.",
	"Rt.",
	"Részvénytársaság",
	"S. de R.L.",
	"S. de R.L. de C.V.",
	"S. en C.",
	"S. en C. de C.V.",
	"S. en C. por A.",
	"S. en C. por A. de C.V.",
	"S.A.",
	"S.A. de C.V.",
	"S.A./N.V.",
	"S.A.B.",
	"S.A.B. de C.V.",
	"S.A.D.",
	"S.A.L.",
	"S.A.P.",
	"S.A.P.I.",
	"S.A.P.I. de C.V.",
	"S.A.R.F.",
	"S.A.R.L.",
	"S.A.U.",
	"S.C.",
	"S.C.C.",
	"S.C.P.",
	"S.C.e.I.",
	"S.Coop.",
	"S.Cra.",
	"S.E.",
	"S.F.",
	"S.G.R.",
	"S.K.A.",
	"S.L.",
	"S.L.L.",
	"S.L.N.E.",
	"S.L.P.",
	"S.L.U.",
	"S.P.R.L.",
	"S.P.R.L.U.",
	"S.R.L.",
	"S.R.L. de C.V.",
	"S.c.r.l.",
	"S.p.A.",
	"S.r.l.",
	"S.À.R.L.",
	"S.à r.l.",
	"SA/NV",
	"SAS",
	"SC",
	"SECS",
	"SGPS",
	"SIA",
	"SM Pte. Ltd.",
	"SNC",
	"SRL",
	"Samostojni podjetnik",
	"Sdn. Bhd.",
	"Sendirian Berhad",
	"Sh.A.",
	"Sh.p.k.",
	"Shoqeri Aksionere",
	"Shoqeri me pergjegjesi te kufizuar",
	"Single Member Private Limited Company",
	"Soc. Col.",
	"Soc.Col.",
	"Sociedad Anónima",
	"Sociedad Anónima Bursátil de Capital Variable",
	"Sociedad Anónima Deportiva",
	"Sociedad Anónima Laboral",
	"Sociedad Anónima Promotora de Inversion de Capital Variable",
	"Sociedad Anónima Unipersonal",
	"Sociedad Civil Particular",
	"Sociedad Civil Privada",
	"Sociedad Colectiva",
	"Sociedad Comanditaria",
	"Sociedad Cooperativa",
	"Sociedad Limitada",
	"Sociedad Limitada Laboral",
	"Sociedad Limitada Nueva Empresa",
	"Sociedad Limitada Personal",
	"Sociedad Limitada Unipersonal",
	"Sociedad de Ahorro y Prestamo",
	"Sociedad de Capital e Industria",
	"Sociedad de Garantía Reciproca",
	"Sociedad de Resposabilidad Limitada",
	"Sociedad del Estado",
	"Sociedad en Comandita Simple",
	"Sociedad en Comandita por Acciones",
	"Sociedad en Nombre Colectivo",
	"Sociedade Fechada",
	"Sociedade Gestora de Participações Sociais",
	"Sociedade anônima",
	"Sociedade limitada",
	"Società a responsabilità limitata",
	"Società cooperativa a responsabilità limitata",
	"Società per Azioni",
	"Société anonyme",
	"Société commerciale canadienne",
	"Société en commandite",
	"Société en commandite simple",
	"Société en nom collectif",
	"Société par actions de régime fédéral",
	"Société par actions simplifiée",
	"Société privée à responsabilité limitée",
	"Société privée à responsabilité limitée unipersonnelle",
	"Société à responsabilité limitée",
	"Sp. z o.o.",
	"Sp. z o.o. S.K.A.",
	"Sp. z o.o. Sp.k.",
	"Sp. z.o.o.",
	"Sp. z.o.o. S.K.A.",
	"Sp. z.o.o. Sp.k.",
	"Sp. zo.o.",
	"Sp. zo.o. S.K.A.",
	"Sp. zo.o. Sp.k.",
	"Sp. zo.o.S.K.A.",
	"Sp. zo.o.Sp.k.",
	"Sp.k.",
	"Sp.zo.o.",
	"Sp.zo.o. S.K.A.",
	"Sp.zo.o. Sp.k.",
	"Sp.zo.o.S.K.A.",
	"Sp.zo.o.Sp.k.",
	"Společnost s ručením omezeným",
	"SàRL",
	"TK",
	"TOV",
	"Tokumei Kumiai",
	"Toshi Jigyo Yugen Sekinin Kumiai",
	"ULC",
	"Unlimited Liability Corporation",
	"Unlimited Proprietary",
	"V.O.F.",
	"VZW",
	"Vennootschap",
	"Vennootschap onder firma",
	"Vereinigung ohne Gewinnerzielungsabsicht",
	"Vereniging zonder winstoogmerk",
	"VoG",
	"W.L.L.",
	"With Limited Liability",
	"Y.K.",
	"Yugen Kaisha",
	"Yugen Sekinin Jigyo Kumiai",
	"Yuhan Hoesa",
	"ZAO",
	"Zrt.",
	"Zártkörűen Működő Részvénytársaság",
	"a professional corporation",
	"a professional law corporation",
	"a.p.c",
	"a.p.c.",
	"affiliates",
	"and Co.",
	"and Co. L.L.C.",
	"and Company",
	"apc",
	"associates",
	"association sans but lucratif",
	"chtd",
	"chtd.",
	"co",
	"company",
	"cooperative",
	"corp",
	"corporation",
	"d.d.",
	"d.n.o.",
	"d.o.o.",
	"e.G.",
	"e.K.",
	"e.U.",
	"e.V.",
	"e.c.",
	"e.v.",
	"ehf.",
	"eingetragene Genossenschaft",
	"eingetragene Verein",
	"eingetragener Kaufmann",
	"eingetragenes Einzelunternehmen",
	"einkahlutafélag",
	"foundation",
	"gGmbH",
	"gemeinnützige GmbH",
	"hf.",
	"hlutafélag",
	"holding",
	"holdings",
	"inc",
	"incorporated",
	"k.d.",
	"l.l.p",
	"l.l.p.",
	"limited",
	"limited company",
	"limited liability company",
	"limited liability partnership",
	"limited partnership",
	"llc",
	"llp",
	"lp",
	"ltd",
	"ltd.",
	"m.b.H.",
	"mbH & Co. KG",
	"mbH und Co. KG",
	"no liability",
	"not for profit",
	"offene Gesellschaft",
	"offene Handelsgesellschaft",
	"ohf.",
	"opinbert hlutafélag",
	"org",
	"org.",
	"p.a",
	"p.a.",
	"p.c",
	"p.l.c",
	"p.l.c.",
	"pa",
	"partners",
	"plc",
	"pllc",
	"private company",
	"private limited company",
	"proprietary limited",
	"psc",
	"psc.",
	"pte",
	"pte ltd",
	"pte.",
	"public company",
	"public limited company",
	"pvt",
	"pvt ltd",
	"pvt.",
	"s.c.",
	"s.p.",
	"s.r.o.",
	"sameignarfélag",
	"sdn",
	"ses.",
	"sf.",
	"sjálfseignarstofnun",
	"société",
	"société en commandite",
	"sp.j.",
	"sp.p.",
	"spółka akcyjna",
	"spółka cywilna",
	"spółka jawna",
	"spółka komandytowa",
	"spółka komandytowo-akcyjna",
	"spółka partnerska",
	"spółka z ograniczoną odpowiedzialnością",
	"und Co. GmbH",
	"unlimited",
	"unltd",
	"y compañía",
	"y compañía de C.V.",
	"y sucesores",
	"y sucesores de C.V.",
	"АД",
	"АО",
	"АТ",
	"Акционерно дружество",
	"Акционерное общество",
	"Акціонерне Товариство",
	"ГП",
	"ГУП",
	"Государственное унитарное предприятие",
	"Дружество с Ограничена Отговорност",
	"ЕАД",
	"ЕООД",
	"Еднолично Акционерно Дружество",
	"Еднолично Дружество с Ограничена Отговорност",
	"ЗАО",
	"Закрытое акционерное общество",
	"ИП",
	"Индивидуальный предприниматель",
	"ОАО",
	"ООД",
	"ООО",
	"Общество с ограниченной ответственностью",
	"Открытое акционерное общество",
	"ПАО",
	"ПО",
	"Публичное акционерное общество",
	"Публичное общество",
	"ТОВ",
	"شركة",
	"任意組合",
	"分公司",
	"匿名組合",
	"厂",
	"合伙企业",
	"合伙企业有限合伙",
	"合同会社",
	"合名会社",
	"合名會社",
	"合資会社",
	"合資會社",
	"总公司",
	"投資事業有限責任組合",
	"有限会社",
	"有限公司",
	"有限合伙",
	"有限合伙企业",
	"有限會社",
	"有限責任事業組合",
	"有限责任公司",
	"株式会社",
	"株式會社",
	"股份有限公司",
	"유한회사",
	"주식회사",
	"합명회사",
	"합자회사",
}
